Abort if StartAt or next_state is not valid
I was running a workflow with an invalid StartAt
This caused a strange error

before
------

```
lib/floe/workflow.rb:76:in `step_nonblock': undefined method `run_nonblock!' for nil:NilClass (NoMethodError)

      current_state.run_nonblock!
                   ^^^^^^^^^^^^^^
	from lib/floe/workflow.rb:63:in `step'
	from lib/floe/workflow.rb:58:in `run!'
	from exe/floe:37:in `<top (required)>'
```

after
-----

```
{"Error"=>"States.Runtime", "Cause"=>"State \"FirstState\" does not exist"}
```